First release
redcraft-org/RedCraftReboot pull request #2
Opened 2020-11-01 18:03 UTC by Omeganx

First Release:
-Added reboot command.
-Added player countdown to warn players when rebooting.

2020-11-01 18:33 UTC, lululombard requested changes
Typos and formatting issues, variable naming, permissions concerns, and access of plugin instances needs to be checked. Running a linter would probably fix most of this stuff

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/Config.java
> +        defaultRebootMessage = config.getString("reboot-default-message");
`defaultRebootMessage` should be renamed `rebootDefaultMessage`

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/Config.java
> +        System.out.println(maxCooldownMinutes);
Leftover debug

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/Config.java
> +        defaultRebootMessage = config.getString("reboot-default-message");
Also please make sure it's consistent for other config variables

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/Reboot.java
> +public class Reboot implements CommandExecutor {
I would have renamed this class `RebootCommand`

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/Reboot.java
> +                    commandSender.sendMessage("The delay of reboot is now " + Config.maxCooldownMinutes + " minutes");
`String.format()` is better than concatenating strings

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/Reboot.java
> +                if(time>0){
```suggestion
                if (time>0){
```

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/Reboot.java
> +        //Cancel the reboot is there is already a task for it.
```suggestion
        // Cancel the reboot is there is already a task for it.
```

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/Reboot.java
> +
empty lines

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/Reboot.java
> +        {
```suggestion
```

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/Reboot.java
> +        if(args.length > 0 && args[0].equals("cancel") && timeTask != null)
```suggestion
        if (args.length > 0 && args[0].equals("cancel") && timeTask != null) {
```

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/Reboot.java
> +
empty line

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/Reboot.java
> +        //If 1 or 2 arguments(time+reason) are given then we parse them.
```suggestion
        // If 1 or 2 arguments(time+reason) are given then we parse them.
```

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/Reboot.java
> +            //Display the countdown to the players.
```suggestion
            // Display the countdown to the players.
```

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/Reboot.java
> +                //the minimum reboot cooldown must be greater than 10s.
```suggestion
                // The minimum reboot cooldown must be greater than 10s.
```

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/Reboot.java
> +                }else if (time > Config.maxCooldownMinutes) {
```suggestion
                } else if (time > Config.maxCooldownMinutes) {
```

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/Reboot.java
> +                //the maximum reboot cooldown must be smaller than maxColdownMinutes.
```suggestion
                // The maximum reboot cooldown must be smaller than maxColdownMinutes.
```

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/Reboot.java
> +                    //convert minutes to seconds.
```suggestion
                    // Convert minutes to seconds
```

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/Reboot.java
> +                    //run boosbar display + countdown.
```suggestion
                    // Run bossbar display + countdown
```

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/Reboot.java
> +                    String reason = (args.length == 2 ) ? args[1] : Config.defaultRebootMessage;
```suggestion
                    String reason = (args.length == 2) ? args[1] : Config.defaultRebootMessage;
```

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/Reboot.java
> +                {
```suggestion
```

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/Reboot.java
> +                }else
```suggestion
                } else {
```

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/Reboot.java
> +                }else{
```suggestion
                } else {
```

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/Reboot.java
> +        this.plugin = plugin;
You don't need to pass the plugin, you can do `RedCraftReboot.getInstance()`

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/RedCraftReboot.java
> +
Remove onDisable

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/RedCraftReboot.java
> +
missing `getInstance()`

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/TimeTask.java
> +        {
```suggestion
```

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/TimeTask.java
> +        for(Player p : Bukkit.getOnlinePlayers())
```suggestion
        for(Player p : Bukkit.getOnlinePlayers()) {
```

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/TimeTask.java
> +        this.bossbar.setVisible(false);
Methods should not have the `{` on another line

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/TimeTask.java
> +    @Override
Missing space between methods

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/TimeTask.java
> +        if(this.remaining_seconds > 0)
```suggestion
        if (this.remaining_seconds > 0) {
```

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/TimeTask.java
> +        {
```suggestion
```

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/TimeTask.java
> +            bossbar.setProgress((double)(this.remaining_seconds)/(double)(this.total_seconds));
```suggestion
            bossbar.setProgress((double) (this.remaining_seconds) / (double) (this.total_seconds));
```

Also pretty sure you can do the conversion after the division

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/TimeTask.java
> +        this.total_seconds = remaining_seconds;
Use camelCase instead of snake_case for variables

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/TimeTask.java
> +            //10s couter
```suggestion
            // 10s counter
```

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/TimeTask.java
> +            {
```suggestion
```

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/TimeTask.java
> +            if(this.remaining_seconds < 10)
```suggestion
            if (this.remaining_seconds < 10) {
```

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/TimeTask.java
> +                for(Player player : Bukkit.getServer().getOnlinePlayers())
Also `{` on the same line and space between `for` and `(`

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/TimeTask.java
> +            //minute counter.
```suggestion
            // Minute counter
```

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/TimeTask.java
> +            {
Also fix space and `{`

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/TimeTask.java
> +                {
same

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/TimeTask.java
> +                    {
same

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/TimeTask.java
> +        {
same

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/TimeTask.java
> +        {
same

2020-11-01 18:33 UTC, lululombard commented on src/main/resources/config.yml
> +reboot-console-message: "The daily reboot has been scheduled in %minutes% minutes"
missing empty line

2020-11-01 18:33 UTC, lululombard commented on src/main/resources/plugin.yml
> +    permission-message: You don't have redcraftreboot.reboot permission.
missing empty line

2020-11-01 18:33 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/Reboot.java
> +            final String[] args) {
Are you sure you don't need to check permissions? I don't remember if setting them in `plugin.yml` enforces them

2020-11-01 18:38 UTC, lululombard commented on src/main/java/org/redcraft/redcraftreboot/RedCraftReboot.java
> +
Nevermind, keep it but cancel all tasks of the plugin using the PluginManager

2020-11-04 23:36 UTC, lululombard approved these changes

2020-11-08 16:52 UTC, Likyaz approved these changes

2020-11-08 16:59 UTC, merged